#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on October 01, 2022 at 22:15:30.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[139];
extern c_float ldata[238];
extern c_float udata[238];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[139];
extern c_float Dinvscaling[139];
extern c_float Escaling[238];
extern c_float Einvscaling[238];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[377];
extern c_int linsys_solver_P[377];
extern c_float linsys_solver_bp[377];
extern c_float linsys_solver_sol[377];
extern c_float linsys_solver_rho_inv_vec[238];
extern c_int linsys_solver_Pdiag_idx[84];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[84];
extern c_int linsys_solver_AtoKKT[758];
extern c_int linsys_solver_rhotoKKT[238];
extern QDLDL_float linsys_solver_D[377];
extern QDLDL_int linsys_solver_etree[377];
extern QDLDL_int linsys_solver_Lnz[377];
extern QDLDL_int   linsys_solver_iwork[1131];
extern QDLDL_bool  linsys_solver_bwork[377];
extern QDLDL_float linsys_solver_fwork[377];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[139];
extern c_float ysolution[238];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[238];
extern c_float work_rho_inv_vec[238];
extern c_int work_constr_type[238];
extern c_float work_x[139];
extern c_float work_y[238];
extern c_float work_z[238];
extern c_float work_xz_tilde[377];
extern c_float work_x_prev[139];
extern c_float work_z_prev[238];
extern c_float work_Ax[238];
extern c_float work_Px[139];
extern c_float work_Aty[139];
extern c_float work_delta_y[238];
extern c_float work_Atdelta_y[139];
extern c_float work_delta_x[139];
extern c_float work_Pdelta_x[139];
extern c_float work_Adelta_x[238];
extern c_float work_D_temp[139];
extern c_float work_D_temp_A[139];
extern c_float work_E_temp[238];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
